my_list = []
print(my_list)
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print(my_list)
my_list.insert(1,15)
print(my_list)
my_list.extend([50])
my_list.extend([60])
my_list.extend([70])
print(my_list)
my_list.remove(70)
print(my_list)
my_list.sort()
print("ascending order:", my_list)
index_of_30 = my_list.index(30)
print(index_of_30)
